### ISSUE TITLE
Focus issue (cursor won't "blink")

### ISSUE THREAD

**Issue by amivit** [DotNetKit/DotNetKit.Wpf.AutoCompleteComboBox#5] opened 2018-01-17 08:00 UTC
Hello! Awesome package here. Sadly there is a bug where cursor won't blink sometimes. It's only after I type the first letter.

This might be helpful: https://stackoverflow.com/questions/8010272/textbox-cursor-is-not-blinking

**Comment by vain0** [comment] 2018-01-17 13:55
Thanks for your feedback.

## Blink Issue

Is the issue (the cursor not blinking) solved? i.e., is there something to be fixed in the library? If yes, could you give me a small XAML code that reproduce it?

## Dropdown Issue

> I'd like the dropdown to stay open until a users click or presses enter.

As far as I tried, once the dropdown opens, it doesn't close until the (Enter | Ctrl+Space) key press or user's click. Did you mean that when the SelectedItem changed, you want to know whether the user selected it or just moving selection?

Regards,
@vain0

**Comment by amivit** [comment] 2018-01-17 14:07
Thanks for the reply. Your UI component is really nice. Regarding my dropdown issue, I need `SelectedItem` to only be changed to a new object, when the user clicks or hits enter on one of the options. Not just when it is highlighted in the dropdown...

Problem is, in my app, with the current setup I have a bunch of things happening when the object is updated, and it causes UI lag and worse, the dropdown to close. So ideally, I only want the SelectedItem to become a new object when the user actually selects (

**Comment by amivit** [comment] 2018-01-17 14:07
I would give more info for the blink issue, but I don't think you should spend time on it, since it's related to this style code we have applied: https://gist.github.com/amivit/7f4b8e8fe67345c7e6bff3c54861a9cc

**Comment by vain0** [comment] 2018-01-17 15:22
I see. To solve, I think that additional key/click event listeners are necessary, to handle "user's select" strictly. Event listening don't need modification to this library.

Because it doesn't seem easy to correct the behavior of SelectedItem, attached properties will meet your needs. i.e., add new attached property and add event listeners to update its value.

Note that, in MVVM, adding event listener to already-defined control can be done with behaviors (using the Blend library) or WPF attached properties.

And thanks for code-snippet.

**Comment by amivit** [comment] 2018-01-17 15:25
Alrighty, thanks. I will try to modify my code for specific enter/click listening. I'm new to WPF so a lot to learn, but great to hear that it's possible without any need for modifying the library.

**Closed** 2018-01-18 13:00 UTC
